# Site settings
title: HelloABQ! - Spreading Albuquerque Pride - Albuquerque, New Mexico
description: Spreading Albuquerque Pride through tees, hoodies, hats, stickers, sweatshirts, accessories, and so much more!

email: albertlozoya@gmail.com

url: "https://helloabq.com"

logourl: /img/logo.png # Your logo or avatar

author: Albert Lozoya

author_thumbnail: /img/author-thumbnail.jpg # default author avatar

# Theme additions - Please update the default values if you intend to use these variables

google_analytics_id: UA-73787596-1

theme:

  contact:                          # Contact info, leave blank to ignore
    company:  HelloABQ!
    address:  PO Box 67587
    city:     Albuquerque
    state:    NM
    zip:      87193-7587
    country:  USA
    phone:	  505-916-1117
    latlng:   39.733536,-104.992611 # (e.g. '39.733536,-104.992611')
    twitter:  helloabq
    facebook: facebook              # (e.g. 'https://www.facebook.com/facebook')
    github:                         # (e.g. 'https://github.com/github')
    instagram:   helloabq
    flickr:                         # (e.g. 'groups/2772799@N24/')
    linkedin:                       # (e.g. 'company/example')
    youtube:                        # (e.g. 'channel/UCovWO5keLOLcLu8WdO-ABJw')

  authors:                          # Author attribution data
    Albert:
      display_name: Albert Lozoya
      gravatar:     1985af848d639efd74c6af48f242cfa8  # use hash only (e.g. '1985af848d639efd74c6af48f242cfa8')
      email: albertlozoya@gmail.com
      web:   http://www.HelloABQ.com
      twitter:  helloabq
      facebook:                     #
      github:                       #
      instagram:        helloabq
      flickr:                       #
      linkedin:                     #
      youtube:                      #

  disqus_id:        bowtieexample   # From your Add This account (e.g. 'bowtieexample')

  addthis_id:                       # From your Add This account (e.g. 'ra-00000a0a00a00aaa')


# Permalinks
permalink:           /:categories/:title/
relative_permalinks: false

gems: [jekyll-paginate]

# Pagination config
paginate: 5
paginate_path: /page/:num



# Jekyll build/resource locations

# source:  .
# destination: ./_site
# plugins_dir: null
# layouts_dir: ./_layouts
# data_dir:    ./_data
# includes_dir: ./_includes

# Jekyll Handling Reading
include:    [] # Specify files to be included in build that may be otherwise ignored (e.g. '[.htaccess]')

keep_files: [] # Files/Folders located inside the ./_site folder to be retained on build (e.g.'[.git, .svn]')

# Files/Folders to be excluded from generated '_site' folder
exclude:
  - .gitignore
  - .sass-cache
highlighter: false

collections:
  products:
    output: true
    layout: product
